import json
from pyvis.network import Network

def generate_dynamic_linkgraph_dashboard():
    # Initialize PyVis with selection menus enabled
    net = Network(
        height="850px", 
        width="100%", 
        bgcolor="#fdfdfd", 
        font_color="#222222", 
        heading="LinkGraph — Algorithmic Architecture Mapping",
        select_menu=True # Adds an interactive dropdown to isolate specific users live
    )
    
    # Configure smooth physics layout options
    net.barnes_hut(gravity=-5000, central_gravity=0.15, spring_length=160)
    
    # Load dataset
    with open('dataset.json', 'r', encoding='utf-8') as file:
        data = json.load(file)
        
    users = data['users']
    posts = data['posts']
    
    # -------------------------------------------------------------------------
    # LAYER 1: ALGORITHMIC METRIC PRE-COMPUTATION
    # -------------------------------------------------------------------------
    
    # Calculate Feed Engagement & Influence Hub Metrics (Module 3 & 4)
    # Sum up all likes and comments generated by each author node
    user_engagement = {user['id']: 0 for user in users}
    for post in posts:
        author = post['author_id']
        if author in user_engagement:
            # Weighted scale: Likes weight 1, Comments weight 3
            user_engagement[author] += (post.get('likes', 0) * 1) + (post.get('comments', 0) * 3)

    # Calculate 2nd-Degree BFS Recommendations (Module 1 & 2)
    # Map out connections for instant adjacency lookups
    adj_matrix = {user['id']: set(user['connections']) for user in users}
    recommendations_edges = []
    
    for user in users:
        uid = user['id']
        my_friends = adj_matrix[uid]
        candidates = {}
        
        # Traverse to 2nd-degree neighbors (Friends of Friends)
        for friend_id in my_friends:
            if friend_id in adj_matrix:
                for fof_id in adj_matrix[friend_id]:
                    if fof_id != uid and fof_id not in my_friends:
                        candidates[fof_id] = candidates.get(fof_id, 0) + 1
                        
        # Sort candidates by mutual friend counts (Jaccard-inspired heuristic)
        if candidates:
            best_rec = max(candidates, key=candidates.get)
            # To prevent drawing duplicate bidirectional recommendation lines
            if uid < best_rec:
                recommendations_edges.append((uid, best_rec, candidates[best_rec]))

    # -------------------------------------------------------------------------
    # LAYER 2: GRAPH VISUALIZATION ASSEMBLY
    # -------------------------------------------------------------------------
    
    # Step A: Populate Node Profiles with dynamic scaling properties
    for user in users:
        uid = str(user['id'])
        name = user['name']
        skills = user.get('skills', [])
        skills_str = ", ".join(skills)
        
        # Determine Community Cluster classification (Module 3)
        if any(s in ["Machine Learning", "Data Science", "Python", "Graphs"] for s in skills):
            community_group = "AI & Data Intelligence"
        elif any(s in ["Cloud Architecture", "Backend Engineer", "Flask", "DevOps"] for s in skills):
            community_group = "Cloud & Core Infrastructure"
        elif any(s in ["UX Research", "Product Design", "Design Systems"] for s in skills):
            community_group = "Product Strategy & UX"
        else:
            community_group = "Talent & Growth Networks"
            
        # Node Sizing: Base radius 18 + scaled factor of total earned feed engagement
        influence_weight = user_engagement.get(user['id'], 0)
        calculated_node_size = 18 + min(influence_weight / 15, 30)
        
        # Build tooltips
        tooltip_html = f"""
        <div style='font-family: sans-serif; padding: 6px; line-height: 1.3;'>
            <strong style='font-size: 14px; color: #0A66C2;'>{name}</strong><br/>
            <strong>Cluster:</strong> {community_group}<br/>
            <strong>Engagement Score:</strong> {influence_weight} pts<br/>
            <small style='color: #666;'><strong>Skills:</strong> {skills_str}</small>
        </div>
        """
        
        # Add node categorized by group (PyVis applies a coordinated color theme per group)
        net.add_node(
            uid, 
            label=name, 
            title=tooltip_html, 
            group=community_group, 
            size=calculated_node_size
        )
        
    # Step B: Populate Base Core Connection Edges (Solid Lines)
    for user in users:
        uid = str(user['id'])
        for conn_id in user.get('connections', []):
            if user['id'] < conn_id: # Avoid adding redundant duplicate paths
                net.add_edge(uid, str(conn_id), color="#b0bec5", width=1.5, title="Existing Connection")
                
    # Step C: Inject Live Algorithmic Recommendation Links (Dashed Lines)
    for src, dest, mutual_count in recommendations_edges:
        net.add_edge(
            str(src), 
            str(dest), 
            color="#ff5722", # Distinct high-contrast orange line
            width=2.5, 
            style="dashed", 
            title=f"RECOMMENDATION HINT: {mutual_count} Mutual Connections Found via BFS Pathing",
            label="Rec Link"
        )

    # Compile the interactive HTML document
    output_file = "linkgraph_dynamic_dashboard.html"
    net.save_graph(output_file)
    print(f"\n[Success] Dynamic Algorithmic Dashboard built: '{output_file}'")

if __name__ == "__main__":
    generate_dynamic_linkgraph_dashboard()